# Generated by Django 4.2.4 on 2023-10-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
