# Generated by Django 4.2.4 on 2023-10-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_app', '0003_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='user_id',
        ),
    ]
